# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ff6da40bf38137b4ed0d2d097617d18974d66f884e6ad8934ddef3ef9bff4bae46f4fdea11d5f8d6424ca5ffb4ddc7bb301c4dff28774cb8e1bb947e80c59fe

test:
  secret_key_base: 4e02a4439040b880ae90cbee38258848b68e25c874ce488f917aa6c7a5c104bf2d5d769da684e6de0722b06b91ec839d477f7f782d90e747cac2c73af3d28b3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 4e02a4439040b880ae90cbee38258848b68e25c874ce488f917aa6c7a5c104bf2d5d769da684e6de0722b06b91ec839d477f7f782d90e747cac2c73af3d28b3e
